name: smk

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core
  - python=3.11
  - snakemake
  
  # fix for bcftools GSL compatibility
  - gsl
  - libgcc-ng
  - libgfortran-ng
  - openblas
  
  # alignment / variant calling
  - bwa
  - bwa-mem2
  - samtools
  - bcftools
  - htslib
  - pysam
  
  # GATK / Picard
  - gatk4
  - picard
  
  # other bio tools you used
  - seqtk
  - jq
  - graphviz
  - glnexus
  
  # python libs actually needed at runtime
  - pandas
  - numpy
  - pyyaml
  - requests
  - psutil
  - openpyxl
  
  # additional libs
  - matplotlib
  - seaborn   
  - scipy     
  - jinja2    
  
  - pip
  - pip:
      - aioeasywebdav
      - crossmap
      - slacker
      - toposort